"use client"

import { motion } from "framer-motion"
import { Shield, Mic, Code, Check } from "lucide-react"

const services = [
  {
    number: "01",
    badge: "AI Red Teaming",
    badgeColor: "bg-rose-50 text-rose-600",
    borderColor: "border-l-rose-400",
    icon: Shield,
    iconColor: "text-rose-500 bg-rose-50",
    title: "Find and fix vulnerabilities in text-based AI agents",
    description:
      "Automated red teaming covering prompt injection, jailbreaks, data exfiltration, and hallucination. Runtime guardrails that protect in production.",
    features: [
      "50+ attack vectors tested automatically",
      "Bidirectional input & output guardrails",
      "Hallucination detection and grounding",
      "OWASP & NIST compliance mapping",
    ],
  },
  {
    number: "02",
    badge: "Voice Security",
    badgeColor: "bg-amber-50 text-amber-600",
    borderColor: "border-l-amber-400",
    icon: Mic,
    iconColor: "text-amber-500 bg-amber-50",
    title: "Protect voice agents from audio-layer attacks",
    description:
      "Voice-specific red teaming and guardrails for speech-to-speech agents. Detect deepfakes, voice injection, and synthetic speech in real-time.",
    features: [
      "Deepfake and synthetic voice detection",
      "Audio-native prompt injection defense",
      "Voice biometric verification",
      "Works with OpenAI, Twilio, LiveKit",
    ],
  },
  {
    number: "03",
    badge: "Code Security",
    badgeColor: "bg-violet-50 text-violet-600",
    borderColor: "border-l-violet-400",
    icon: Code,
    iconColor: "text-violet-500 bg-violet-50",
    title: "Catch vulnerabilities in AI-generated code before execution",
    description:
      "A lightweight security wrapper that reviews code generated by LLMs. Catches injection vulnerabilities, supply chain risks, and insecure patterns before they ship.",
    features: [
      "Pre-execution code review for LLM outputs",
      "Supply chain risk detection",
      "Insecure pattern identification",
      "Works with Cursor, Copilot, Claude Code",
    ],
  },
]

export function ServicesSection() {
  return (
    <section id="services" className="scroll-mt-24 px-4 py-24 sm:px-6 lg:px-8 lg:py-32">
      <div className="mx-auto max-w-7xl">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center"
        >
          <span className="text-xs font-medium uppercase tracking-widest text-emerald-600">
            Three Pillars
          </span>
          <h2 className="mt-4 text-3xl font-semibold tracking-tight text-gray-900 sm:text-4xl lg:text-5xl">
            Comprehensive security.
            <br />
            Every modality.
          </h2>
          <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-gray-500">
            Purpose-built security for text agents, voice agents, and coding agents.
            Test before deployment, protect at runtime.
          </p>
        </motion.div>

        {/* Service cards */}
        <div className="mt-20 space-y-12">
          {services.map((service, index) => (
            <motion.div
              key={service.number}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              className={`rounded-2xl border border-gray-100 border-l-4 ${service.borderColor} bg-white p-8 lg:p-12`}
            >
              <div className={`grid gap-8 lg:gap-12 ${index % 2 === 1 ? "lg:grid-cols-[1fr_1.2fr]" : "lg:grid-cols-[1.2fr_1fr]"}`}>
                {/* Content side */}
                <div className={index % 2 === 1 ? "lg:order-2" : ""}>
                  <span className="text-6xl font-bold text-gray-100">{service.number}</span>

                  <div className="mt-4">
                    <span className={`inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-medium ${service.badgeColor}`}>
                      <service.icon className="h-3.5 w-3.5" />
                      {service.badge}
                    </span>
                  </div>

                  <h3 className="mt-4 text-2xl font-semibold tracking-tight text-gray-900 lg:text-3xl">
                    {service.title}
                  </h3>

                  <p className="mt-4 text-base leading-relaxed text-gray-500">
                    {service.description}
                  </p>
                </div>

                {/* Features side */}
                <div className={`flex items-center ${index % 2 === 1 ? "lg:order-1" : ""}`}>
                  <ul className="space-y-4">
                    {service.features.map((feature, fIndex) => (
                      <motion.li
                        key={fIndex}
                        initial={{ opacity: 0, x: -10 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.3, delay: 0.3 + fIndex * 0.05 }}
                        className="flex items-start gap-3"
                      >
                        <div className="mt-0.5 rounded-full bg-emerald-50 p-1">
                          <Check className="h-3.5 w-3.5 text-emerald-600" />
                        </div>
                        <span className="text-sm text-gray-600">{feature}</span>
                      </motion.li>
                    ))}
                  </ul>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}
